version: '3.8'
services:
  postgres:
#   TODO Тут можно стильно, модно, молодежно, хотя бы 14ю постгрю воткнуть
    image: postgres:12.20-alpine3.20
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 460461
      POSTGRES_DB: MyLittleProjectDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
